Added test cases for getTitle,setTitle,getImage,setImage
kalyaniIN/Team2-project pull request #2
Opened 2023-12-06 17:44 UTC by kalyaniIN

2023-12-06 17:56 UTC, Uma-Gopalakrishnan requested changes
Product instance can be reused from master

2023-12-06 17:56 UTC, Uma-Gopalakrishnan commented on src/test/java/com/example/produktapi/model/ProductTest.java
> +    // Create a Product instance
Pls remove this code

2023-12-11 10:18 UTC, kalyaniIN commented
I have updated the branch

2023-12-11 15:17 UTC, Uma-Gopalakrishnan approved these changes
Approved

2023-12-11 15:18 UTC, merged